#!/bin/tcsh

set filecount = 0
foreach i (2 4 8 16 32 64)
	foreach j (2 4 8 16 32)
	
		echo >> stats/output
		echo $i $j >> stats/output
		echo >> stats/output
		foreach c (0 1 2 3 4 5 6 7 8 9)
			unix ../samp_proc/out$c $i $j >> stats/output
			@ c = ($c + 1)
		end
			
	
	end
end


